//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Efficio.Net {

public enum JointType {
  None,
  Head,
  ShoulderCenter,
  ShoulderRight,
  ElbowRight,
  WristRight,
  HandRight,
  ShoulderLeft,
  ElbowLeft,
  WristLeft,
  HandLeft,
  Spine,
  HipCenter,
  HipRight,
  KneeRight,
  AnkleRight,
  FootRight,
  HipLeft,
  KneeLeft,
  AnkleLeft,
  FootLeft,
  RightHandThumbIP,
  RightHandThumbMCP,
  RightHandThumbCMP,
  RightHandThumbTIP,
  RightHandIndexMCP,
  RightHandIndexPIP,
  RightHandIndexDIP,
  RightHandIndexTIP,
  RightHandMiddleMCP,
  RightHandMiddlePIP,
  RightHandMiddleDIP,
  RightHandMiddleTIP,
  RightHandRingMCP,
  RightHandRingPIP,
  RightHandRingDIP,
  RightHandRingTIP,
  RightHandPinkyMCP,
  RightHandPinkyPIP,
  RightHandPinkyDIP,
  RightHandPinkyTIP,
  LeftHandThumbIP,
  LeftHandThumbMCP,
  LeftHandThumbCMP,
  LeftHandThumbTIP,
  LeftHandIndexMCP,
  LeftHandIndexPIP,
  LeftHandIndexDIP,
  LeftHandIndexTIP,
  LeftHandMiddleMCP,
  LeftHandMiddlePIP,
  LeftHandMiddleDIP,
  LeftHandMiddleTIP,
  LeftHandRingMCP,
  LeftHandRingPIP,
  LeftHandRingDIP,
  LeftHandRingTIP,
  LeftHandPinkyMCP,
  LeftHandPinkyPIP,
  LeftHandPinkyDIP,
  LeftHandPinkyTIP
}

}
