/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif



#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


	 /* Includes the header in the wrapper code */
	#include <memory>
	#include "Event.h"
	#include "Vector3.h"
	#include "Frame.h"
	#include "Enumerations.h"
	#include "PinchEvent.h"
	#include "EfficioFrame.h"
	#include "Engine.h"
 

#include <string>


#include <stdexcept>


#include <vector>
#include <stdexcept>


struct SWIG_null_deleter {
  void operator() (void const *) const {
  }
};
#define SWIG_NO_NULL_DELETER_0 , SWIG_null_deleter()
#define SWIG_NO_NULL_DELETER_1
#define SWIG_NO_NULL_DELETER_SWIG_POINTER_NEW
#define SWIG_NO_NULL_DELETER_SWIG_POINTER_OWN

SWIGINTERN std::vector< std::shared_ptr< Efficio::Event > >::const_reference std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__get(std::vector< std::shared_ptr< Efficio::Event > > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__set(std::vector< std::shared_ptr< Efficio::Event > > *self,int i,std::vector< std::shared_ptr< Efficio::Event > >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_new_1Vector3(JNIEnv *jenv, jclass jcls, jfloat jarg1, jfloat jarg2, jfloat jarg3) {
  jlong jresult = 0 ;
  float arg1 ;
  float arg2 ;
  float arg3 ;
  Efficio::Vector3 *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (float)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  result = (Efficio::Vector3 *)new Efficio::Vector3(arg1,arg2,arg3);
  *(Efficio::Vector3 **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_delete_1Vector3(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Efficio::Vector3 *arg1 = (Efficio::Vector3 *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Efficio::Vector3 **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jfloat JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_Vector3_1X(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  Efficio::Vector3 *arg1 = (Efficio::Vector3 *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Efficio::Vector3 **)&jarg1; 
  result = (float)(arg1)->X();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_Vector3_1Y(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  Efficio::Vector3 *arg1 = (Efficio::Vector3 *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Efficio::Vector3 **)&jarg1; 
  result = (float)(arg1)->Y();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_Vector3_1Z(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  Efficio::Vector3 *arg1 = (Efficio::Vector3 *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Efficio::Vector3 **)&jarg1; 
  result = (float)(arg1)->Z();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_new_1Event(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Efficio::Event *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Efficio::Event *)new Efficio::Event();
  
  *(std::shared_ptr<  Efficio::Event > **)&jresult = result ? new std::shared_ptr<  Efficio::Event >(result SWIG_NO_NULL_DELETER_1) : 0;
  
  return jresult;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_delete_1Event(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Efficio::Event *arg1 = (Efficio::Event *) 0 ;
  std::shared_ptr< Efficio::Event > *smartarg1 = 0 ;
  
  (void)jenv;
  (void)jcls;
  
  smartarg1 = *(std::shared_ptr<  Efficio::Event > **)&jarg1;
  arg1 = (Efficio::Event *)(smartarg1 ? smartarg1->get() : 0); 
  (void)arg1; delete smartarg1;
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_new_1Frame(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Efficio::Frame *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Efficio::Frame *)new Efficio::Frame();
  *(Efficio::Frame **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_delete_1Frame(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Efficio::Frame *arg1 = (Efficio::Frame *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Efficio::Frame **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_new_1PinchEvent(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  Efficio::Body::BodySide arg1 ;
  SwigValueWrapper< Efficio::Vector3 > arg2 ;
  Efficio::Vector3 *argp2 ;
  Efficio::Body::Hands::PinchEvent *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = (Efficio::Body::BodySide)jarg1; 
  argp2 = *(Efficio::Vector3 **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null Efficio::Vector3");
    return 0;
  }
  arg2 = *argp2; 
  result = (Efficio::Body::Hands::PinchEvent *)new Efficio::Body::Hands::PinchEvent(arg1,arg2);
  
  *(std::shared_ptr<  Efficio::Body::Hands::PinchEvent > **)&jresult = result ? new std::shared_ptr<  Efficio::Body::Hands::PinchEvent >(result SWIG_NO_NULL_DELETER_1) : 0;
  
  return jresult;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_delete_1PinchEvent(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  
  (void)jenv;
  (void)jcls;
  
  smartarg1 = *(std::shared_ptr<  Efficio::Body::Hands::PinchEvent > **)&jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  (void)arg1; delete smartarg1;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_PinchEvent_1Side_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  Efficio::Body::BodySide arg2 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  
  smartarg1 = *(std::shared_ptr<  Efficio::Body::Hands::PinchEvent > **)&jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (Efficio::Body::BodySide)jarg2; 
  if (arg1) (arg1)->Side = arg2;
}


SWIGEXPORT jint JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_PinchEvent_1Side_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  Efficio::Body::BodySide result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  
  smartarg1 = *(std::shared_ptr<  Efficio::Body::Hands::PinchEvent > **)&jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  result = (Efficio::Body::BodySide) ((arg1)->Side);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_PinchEvent_1Finger1_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  std::string *arg2 = 0 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  
  smartarg1 = *(std::shared_ptr<  Efficio::Body::Hands::PinchEvent > **)&jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->Finger1 = *arg2;
}


SWIGEXPORT jstring JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_PinchEvent_1Finger1_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  
  smartarg1 = *(std::shared_ptr<  Efficio::Body::Hands::PinchEvent > **)&jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  result = (std::string *) & ((arg1)->Finger1);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_PinchEvent_1Finger2_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  std::string *arg2 = 0 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  
  smartarg1 = *(std::shared_ptr<  Efficio::Body::Hands::PinchEvent > **)&jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->Finger2 = *arg2;
}


SWIGEXPORT jstring JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_PinchEvent_1Finger2_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  
  smartarg1 = *(std::shared_ptr<  Efficio::Body::Hands::PinchEvent > **)&jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  result = (std::string *) & ((arg1)->Finger2);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_PinchEvent_1Position_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  Efficio::Vector3 *arg2 = (Efficio::Vector3 *) 0 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  
  smartarg1 = *(std::shared_ptr<  Efficio::Body::Hands::PinchEvent > **)&jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = *(Efficio::Vector3 **)&jarg2; 
  if (arg1) (arg1)->Position = *arg2;
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_PinchEvent_1Position_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  Efficio::Vector3 *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  
  smartarg1 = *(std::shared_ptr<  Efficio::Body::Hands::PinchEvent > **)&jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  result = (Efficio::Vector3 *)& ((arg1)->Position);
  *(Efficio::Vector3 **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_new_1EfficioFrame(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Efficio::EfficioFrame *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Efficio::EfficioFrame *)new Efficio::EfficioFrame();
  *(Efficio::EfficioFrame **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_delete_1EfficioFrame(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Efficio::EfficioFrame *arg1 = (Efficio::EfficioFrame *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Efficio::EfficioFrame **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_EfficioFrame_1GetEvents(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Efficio::EfficioFrame *arg1 = (Efficio::EfficioFrame *) 0 ;
  std::vector< std::shared_ptr< Efficio::Event > > result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Efficio::EfficioFrame **)&jarg1; 
  result = (arg1)->GetEvents();
  *(std::vector< std::shared_ptr< Efficio::Event > > **)&jresult = new std::vector< std::shared_ptr< Efficio::Event > >((const std::vector< std::shared_ptr< Efficio::Event > > &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_EfficioFrame_1AddEvent(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  Efficio::EfficioFrame *arg1 = (Efficio::EfficioFrame *) 0 ;
  Efficio::Event *arg2 = (Efficio::Event *) 0 ;
  std::shared_ptr< Efficio::Event > *smartarg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Efficio::EfficioFrame **)&jarg1; 
  
  smartarg2 = *(std::shared_ptr<  Efficio::Event > **)&jarg2;
  arg2 = (Efficio::Event *)(smartarg2 ? smartarg2->get() : 0); 
  (arg1)->AddEvent(arg2);
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_new_1Engine(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Efficio::Engine *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Efficio::Engine *)new Efficio::Engine();
  *(Efficio::Engine **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_delete_1Engine(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Efficio::Engine *arg1 = (Efficio::Engine *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Efficio::Engine **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_Engine_1Start(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Efficio::Engine *arg1 = (Efficio::Engine *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Efficio::Engine **)&jarg1; 
  (arg1)->Start();
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_Engine_1GetFrame(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Efficio::Engine *arg1 = (Efficio::Engine *) 0 ;
  Efficio::EfficioFrame result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Efficio::Engine **)&jarg1; 
  result = (arg1)->GetFrame();
  *(Efficio::EfficioFrame **)&jresult = new Efficio::EfficioFrame((const Efficio::EfficioFrame &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_Engine_1DeviceConfiguration_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  Efficio::Engine *arg1 = (Efficio::Engine *) 0 ;
  Efficio::Configuration::DeviceConfiguration *arg2 = (Efficio::Configuration::DeviceConfiguration *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Efficio::Engine **)&jarg1; 
  arg2 = *(Efficio::Configuration::DeviceConfiguration **)&jarg2; 
  if (arg1) (arg1)->DeviceConfiguration = *arg2;
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_Engine_1DeviceConfiguration_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Efficio::Engine *arg1 = (Efficio::Engine *) 0 ;
  Efficio::Configuration::DeviceConfiguration *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Efficio::Engine **)&jarg1; 
  result = (Efficio::Configuration::DeviceConfiguration *)& ((arg1)->DeviceConfiguration);
  *(Efficio::Configuration::DeviceConfiguration **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_new_1LeapConfiguration(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Efficio::Configuration::LeapConfiguration *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Efficio::Configuration::LeapConfiguration *)new Efficio::Configuration::LeapConfiguration();
  *(Efficio::Configuration::LeapConfiguration **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_delete_1LeapConfiguration(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Efficio::Configuration::LeapConfiguration *arg1 = (Efficio::Configuration::LeapConfiguration *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Efficio::Configuration::LeapConfiguration **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_LeapConfiguration_1Enabled_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  Efficio::Configuration::LeapConfiguration *arg1 = (Efficio::Configuration::LeapConfiguration *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Efficio::Configuration::LeapConfiguration **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->Enabled = arg2;
}


SWIGEXPORT jboolean JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_LeapConfiguration_1Enabled_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  Efficio::Configuration::LeapConfiguration *arg1 = (Efficio::Configuration::LeapConfiguration *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Efficio::Configuration::LeapConfiguration **)&jarg1; 
  result = (bool) ((arg1)->Enabled);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_new_1DeviceConfiguration(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Efficio::Configuration::DeviceConfiguration *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Efficio::Configuration::DeviceConfiguration *)new Efficio::Configuration::DeviceConfiguration();
  *(Efficio::Configuration::DeviceConfiguration **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_delete_1DeviceConfiguration(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Efficio::Configuration::DeviceConfiguration *arg1 = (Efficio::Configuration::DeviceConfiguration *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Efficio::Configuration::DeviceConfiguration **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_DeviceConfiguration_1LeapConfiguration_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  Efficio::Configuration::DeviceConfiguration *arg1 = (Efficio::Configuration::DeviceConfiguration *) 0 ;
  Efficio::Configuration::LeapConfiguration *arg2 = (Efficio::Configuration::LeapConfiguration *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Efficio::Configuration::DeviceConfiguration **)&jarg1; 
  arg2 = *(Efficio::Configuration::LeapConfiguration **)&jarg2; 
  if (arg1) (arg1)->LeapConfiguration = *arg2;
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_DeviceConfiguration_1LeapConfiguration_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Efficio::Configuration::DeviceConfiguration *arg1 = (Efficio::Configuration::DeviceConfiguration *) 0 ;
  Efficio::Configuration::LeapConfiguration *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Efficio::Configuration::DeviceConfiguration **)&jarg1; 
  result = (Efficio::Configuration::LeapConfiguration *)& ((arg1)->LeapConfiguration);
  *(Efficio::Configuration::LeapConfiguration **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_new_1EventCollection_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  std::vector< std::shared_ptr< Efficio::Event > > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (std::vector< std::shared_ptr< Efficio::Event > > *)new std::vector< std::shared_ptr< Efficio::Event > >();
  *(std::vector< std::shared_ptr< Efficio::Event > > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_new_1EventCollection_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  std::vector< std::shared_ptr< Efficio::Event > >::size_type arg1 ;
  std::vector< std::shared_ptr< Efficio::Event > > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > >::size_type)jarg1; 
  result = (std::vector< std::shared_ptr< Efficio::Event > > *)new std::vector< std::shared_ptr< Efficio::Event > >(arg1);
  *(std::vector< std::shared_ptr< Efficio::Event > > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_EventCollection_1size(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  std::vector< std::shared_ptr< Efficio::Event > >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< std::shared_ptr< Efficio::Event > > **)&jarg1; 
  result = ((std::vector< std::shared_ptr< Efficio::Event > > const *)arg1)->size();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_EventCollection_1capacity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  std::vector< std::shared_ptr< Efficio::Event > >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< std::shared_ptr< Efficio::Event > > **)&jarg1; 
  result = ((std::vector< std::shared_ptr< Efficio::Event > > const *)arg1)->capacity();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_EventCollection_1reserve(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  std::vector< std::shared_ptr< Efficio::Event > >::size_type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< std::shared_ptr< Efficio::Event > > **)&jarg1; 
  arg2 = (std::vector< std::shared_ptr< Efficio::Event > >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT jboolean JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_EventCollection_1isEmpty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< std::shared_ptr< Efficio::Event > > **)&jarg1; 
  result = (bool)((std::vector< std::shared_ptr< Efficio::Event > > const *)arg1)->empty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_EventCollection_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< std::shared_ptr< Efficio::Event > > **)&jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_EventCollection_1add(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  std::vector< std::shared_ptr< Efficio::Event > >::value_type *arg2 = 0 ;
  std::vector< std::shared_ptr< Efficio::Event > >::value_type tempnull2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(std::vector< std::shared_ptr< Efficio::Event > > **)&jarg1; 
  arg2 = jarg2 ? *(std::vector< std::shared_ptr< Efficio::Event > >::value_type **)&jarg2 : &tempnull2; 
  (arg1)->push_back((std::vector< std::shared_ptr< Efficio::Event > >::value_type const &)*arg2);
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_EventCollection_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  int arg2 ;
  std::vector< std::shared_ptr< Efficio::Event > >::value_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< std::shared_ptr< Efficio::Event > > **)&jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< std::shared_ptr< Efficio::Event > >::value_type *) &std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__get(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  
  *(std::vector< std::shared_ptr< Efficio::Event > >::value_type **)&jresult = *result ? new std::shared_ptr< Efficio::Event >(*result) : 0; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_EventCollection_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  int arg2 ;
  std::vector< std::shared_ptr< Efficio::Event > >::value_type *arg3 = 0 ;
  std::vector< std::shared_ptr< Efficio::Event > >::value_type tempnull3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(std::vector< std::shared_ptr< Efficio::Event > > **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = jarg3 ? *(std::vector< std::shared_ptr< Efficio::Event > >::value_type **)&jarg3 : &tempnull3; 
  try {
    std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__set(arg1,arg2,(std::shared_ptr< Efficio::Event > const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_delete_1EventCollection(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::vector< std::shared_ptr< Efficio::Event > > **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_PinchEvent_1SWIGSmartPtrUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    std::shared_ptr< Efficio::Body::Hands::PinchEvent > *argp1;
    (void)jenv;
    (void)jcls;
    argp1 = *(std::shared_ptr< Efficio::Body::Hands::PinchEvent > **)&jarg1;
    *(std::shared_ptr< Efficio::Event > **)&baseptr = argp1 ? new std::shared_ptr< Efficio::Event >(*argp1) : 0;
    return baseptr;
}

SWIGEXPORT jlong JNICALL Java_Efficio_Runtime_EfficioRuntimeJNI_EfficioFrame_1SWIGUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(Efficio::Frame **)&baseptr = *(Efficio::EfficioFrame **)&jarg1;
    return baseptr;
}

#ifdef __cplusplus
}
#endif

