/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif



#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_EfficioRuntime(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_EfficioRuntime(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_EfficioRuntime(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


	 /* Includes the header in the wrapper code */
	#include <memory>
	#include "Event.h"
	#include "Vector3.h"
	#include "Frame.h"
	#include "Enumerations.h"
	#include "PinchEvent.h"
	#include "EfficioFrame.h"
	#include "Engine.h"
 

#include <string>


#include <stdexcept>


#include <vector>
#include <algorithm>
#include <stdexcept>


struct SWIG_null_deleter {
  void operator() (void const *) const {
  }
};
#define SWIG_NO_NULL_DELETER_0 , SWIG_null_deleter()
#define SWIG_NO_NULL_DELETER_1
#define SWIG_NO_NULL_DELETER_SWIG_POINTER_NEW
#define SWIG_NO_NULL_DELETER_SWIG_POINTER_OWN

SWIGINTERN std::vector< std::shared_ptr< Efficio::Event > > *new_std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg___SWIG_2(int capacity){
        std::vector< std::shared_ptr< Efficio::Event > >* pv = 0;
        if (capacity >= 0) {
          pv = new std::vector< std::shared_ptr< Efficio::Event > >();
          pv->reserve(capacity);
       } else {
          throw std::out_of_range("capacity");
       }
       return pv;
      }
SWIGINTERN std::shared_ptr< Efficio::Event > std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__getitemcopy(std::vector< std::shared_ptr< Efficio::Event > > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN std::shared_ptr< Efficio::Event > const &std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__getitem(std::vector< std::shared_ptr< Efficio::Event > > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__setitem(std::vector< std::shared_ptr< Efficio::Event > > *self,int index,std::shared_ptr< Efficio::Event > const &val){
        if (index>=0 && index<(int)self->size())
          (*self)[index] = val;
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__AddRange(std::vector< std::shared_ptr< Efficio::Event > > *self,std::vector< std::shared_ptr< Efficio::Event > > const &values){
        self->insert(self->end(), values.begin(), values.end());
      }
SWIGINTERN std::vector< std::shared_ptr< Efficio::Event > > *std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__GetRange(std::vector< std::shared_ptr< Efficio::Event > > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        return new std::vector< std::shared_ptr< Efficio::Event > >(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__Insert(std::vector< std::shared_ptr< Efficio::Event > > *self,int index,std::shared_ptr< Efficio::Event > const &x){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, x);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__InsertRange(std::vector< std::shared_ptr< Efficio::Event > > *self,int index,std::vector< std::shared_ptr< Efficio::Event > > const &values){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, values.begin(), values.end());
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__RemoveAt(std::vector< std::shared_ptr< Efficio::Event > > *self,int index){
        if (index>=0 && index<(int)self->size())
          self->erase(self->begin() + index);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__RemoveRange(std::vector< std::shared_ptr< Efficio::Event > > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        self->erase(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN std::vector< std::shared_ptr< Efficio::Event > > *std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__Repeat(std::shared_ptr< Efficio::Event > const &value,int count){
        if (count < 0)
          throw std::out_of_range("count");
        return new std::vector< std::shared_ptr< Efficio::Event > >(count, value);
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__Reverse__SWIG_0(std::vector< std::shared_ptr< Efficio::Event > > *self){
        std::reverse(self->begin(), self->end());
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__Reverse__SWIG_1(std::vector< std::shared_ptr< Efficio::Event > > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        std::reverse(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__SetRange(std::vector< std::shared_ptr< Efficio::Event > > *self,int index,std::vector< std::shared_ptr< Efficio::Event > > const &values){
        if (index < 0)
          throw std::out_of_range("index");
        if (index+values.size() > self->size())
          throw std::out_of_range("index");
        std::copy(values.begin(), values.end(), self->begin()+index);
      }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_new_Vector3___(float jarg1, float jarg2, float jarg3) {
  void * jresult ;
  float arg1 ;
  float arg2 ;
  float arg3 ;
  Efficio::Vector3 *result = 0 ;
  
  arg1 = (float)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  result = (Efficio::Vector3 *)new Efficio::Vector3(arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_delete_Vector3___(void * jarg1) {
  Efficio::Vector3 *arg1 = (Efficio::Vector3 *) 0 ;
  
  arg1 = (Efficio::Vector3 *)jarg1; 
  delete arg1;
}


SWIGEXPORT float SWIGSTDCALL CSharp_EfficiofRuntime_Vector3_X___(void * jarg1) {
  float jresult ;
  Efficio::Vector3 *arg1 = (Efficio::Vector3 *) 0 ;
  float result;
  
  arg1 = (Efficio::Vector3 *)jarg1; 
  result = (float)(arg1)->X();
  jresult = result; 
  return jresult;
}


SWIGEXPORT float SWIGSTDCALL CSharp_EfficiofRuntime_Vector3_Y___(void * jarg1) {
  float jresult ;
  Efficio::Vector3 *arg1 = (Efficio::Vector3 *) 0 ;
  float result;
  
  arg1 = (Efficio::Vector3 *)jarg1; 
  result = (float)(arg1)->Y();
  jresult = result; 
  return jresult;
}


SWIGEXPORT float SWIGSTDCALL CSharp_EfficiofRuntime_Vector3_Z___(void * jarg1) {
  float jresult ;
  Efficio::Vector3 *arg1 = (Efficio::Vector3 *) 0 ;
  float result;
  
  arg1 = (Efficio::Vector3 *)jarg1; 
  result = (float)(arg1)->Z();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_new_Event___() {
  void * jresult ;
  Efficio::Event *result = 0 ;
  
  result = (Efficio::Event *)new Efficio::Event();
  
  jresult = result ? new std::shared_ptr<  Efficio::Event >(result SWIG_NO_NULL_DELETER_1) : 0;
  
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_delete_Event___(void * jarg1) {
  Efficio::Event *arg1 = (Efficio::Event *) 0 ;
  std::shared_ptr< Efficio::Event > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Efficio::Event > *)jarg1;
  arg1 = (Efficio::Event *)(smartarg1 ? smartarg1->get() : 0); 
  (void)arg1; delete smartarg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_new_Frame___() {
  void * jresult ;
  Efficio::Frame *result = 0 ;
  
  result = (Efficio::Frame *)new Efficio::Frame();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_delete_Frame___(void * jarg1) {
  Efficio::Frame *arg1 = (Efficio::Frame *) 0 ;
  
  arg1 = (Efficio::Frame *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_new_PinchEvent___(int jarg1, void * jarg2) {
  void * jresult ;
  Efficio::Body::BodySide arg1 ;
  SwigValueWrapper< Efficio::Vector3 > arg2 ;
  Efficio::Vector3 *argp2 ;
  Efficio::Body::Hands::PinchEvent *result = 0 ;
  
  arg1 = (Efficio::Body::BodySide)jarg1; 
  argp2 = (Efficio::Vector3 *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Efficio::Vector3", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (Efficio::Body::Hands::PinchEvent *)new Efficio::Body::Hands::PinchEvent(arg1,arg2);
  
  jresult = result ? new std::shared_ptr<  Efficio::Body::Hands::PinchEvent >(result SWIG_NO_NULL_DELETER_1) : 0;
  
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_delete_PinchEvent___(void * jarg1) {
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Efficio::Body::Hands::PinchEvent > *)jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  (void)arg1; delete smartarg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_PinchEvent_Side_set___(void * jarg1, int jarg2) {
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  Efficio::Body::BodySide arg2 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Efficio::Body::Hands::PinchEvent > *)jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (Efficio::Body::BodySide)jarg2; 
  if (arg1) (arg1)->Side = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_EfficiofRuntime_PinchEvent_Side_get___(void * jarg1) {
  int jresult ;
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  Efficio::Body::BodySide result;
  
  
  smartarg1 = (std::shared_ptr<  Efficio::Body::Hands::PinchEvent > *)jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  result = (Efficio::Body::BodySide) ((arg1)->Side);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_PinchEvent_Finger1_set___(void * jarg1, char * jarg2) {
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  std::string *arg2 = 0 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Efficio::Body::Hands::PinchEvent > *)jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return ;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  if (arg1) (arg1)->Finger1 = *arg2;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_EfficiofRuntime_PinchEvent_Finger1_get___(void * jarg1) {
  char * jresult ;
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  std::string *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Efficio::Body::Hands::PinchEvent > *)jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  result = (std::string *) & ((arg1)->Finger1);
  jresult = SWIG_csharp_string_callback(result->c_str()); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_PinchEvent_Finger2_set___(void * jarg1, char * jarg2) {
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  std::string *arg2 = 0 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Efficio::Body::Hands::PinchEvent > *)jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return ;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  if (arg1) (arg1)->Finger2 = *arg2;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_EfficiofRuntime_PinchEvent_Finger2_get___(void * jarg1) {
  char * jresult ;
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  std::string *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Efficio::Body::Hands::PinchEvent > *)jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  result = (std::string *) & ((arg1)->Finger2);
  jresult = SWIG_csharp_string_callback(result->c_str()); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_PinchEvent_Position_set___(void * jarg1, void * jarg2) {
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  Efficio::Vector3 *arg2 = (Efficio::Vector3 *) 0 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Efficio::Body::Hands::PinchEvent > *)jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (Efficio::Vector3 *)jarg2; 
  if (arg1) (arg1)->Position = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_PinchEvent_Position_get___(void * jarg1) {
  void * jresult ;
  Efficio::Body::Hands::PinchEvent *arg1 = (Efficio::Body::Hands::PinchEvent *) 0 ;
  std::shared_ptr< Efficio::Body::Hands::PinchEvent > *smartarg1 = 0 ;
  Efficio::Vector3 *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Efficio::Body::Hands::PinchEvent > *)jarg1;
  arg1 = (Efficio::Body::Hands::PinchEvent *)(smartarg1 ? smartarg1->get() : 0); 
  result = (Efficio::Vector3 *)& ((arg1)->Position);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_new_EfficioFrame___() {
  void * jresult ;
  Efficio::EfficioFrame *result = 0 ;
  
  result = (Efficio::EfficioFrame *)new Efficio::EfficioFrame();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_delete_EfficioFrame___(void * jarg1) {
  Efficio::EfficioFrame *arg1 = (Efficio::EfficioFrame *) 0 ;
  
  arg1 = (Efficio::EfficioFrame *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_EfficioFrame_GetEvents___(void * jarg1) {
  void * jresult ;
  Efficio::EfficioFrame *arg1 = (Efficio::EfficioFrame *) 0 ;
  std::vector< std::shared_ptr< Efficio::Event > > result;
  
  arg1 = (Efficio::EfficioFrame *)jarg1; 
  result = (arg1)->GetEvents();
  jresult = new std::vector< std::shared_ptr< Efficio::Event > >((const std::vector< std::shared_ptr< Efficio::Event > > &)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_EfficioFrame_AddEvent___(void * jarg1, void * jarg2) {
  Efficio::EfficioFrame *arg1 = (Efficio::EfficioFrame *) 0 ;
  Efficio::Event *arg2 = (Efficio::Event *) 0 ;
  std::shared_ptr< Efficio::Event > *smartarg2 = 0 ;
  
  arg1 = (Efficio::EfficioFrame *)jarg1; 
  
  smartarg2 = (std::shared_ptr<  Efficio::Event > *)jarg2;
  arg2 = (Efficio::Event *)(smartarg2 ? smartarg2->get() : 0); 
  (arg1)->AddEvent(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_new_Engine___() {
  void * jresult ;
  Efficio::Engine *result = 0 ;
  
  result = (Efficio::Engine *)new Efficio::Engine();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_delete_Engine___(void * jarg1) {
  Efficio::Engine *arg1 = (Efficio::Engine *) 0 ;
  
  arg1 = (Efficio::Engine *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_Engine_Start___(void * jarg1) {
  Efficio::Engine *arg1 = (Efficio::Engine *) 0 ;
  
  arg1 = (Efficio::Engine *)jarg1; 
  (arg1)->Start();
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_Engine_GetFrame___(void * jarg1) {
  void * jresult ;
  Efficio::Engine *arg1 = (Efficio::Engine *) 0 ;
  Efficio::EfficioFrame result;
  
  arg1 = (Efficio::Engine *)jarg1; 
  result = (arg1)->GetFrame();
  jresult = new Efficio::EfficioFrame((const Efficio::EfficioFrame &)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_Engine_DeviceConfiguration_set___(void * jarg1, void * jarg2) {
  Efficio::Engine *arg1 = (Efficio::Engine *) 0 ;
  Efficio::Configuration::DeviceConfiguration *arg2 = (Efficio::Configuration::DeviceConfiguration *) 0 ;
  
  arg1 = (Efficio::Engine *)jarg1; 
  arg2 = (Efficio::Configuration::DeviceConfiguration *)jarg2; 
  if (arg1) (arg1)->DeviceConfiguration = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_Engine_DeviceConfiguration_get___(void * jarg1) {
  void * jresult ;
  Efficio::Engine *arg1 = (Efficio::Engine *) 0 ;
  Efficio::Configuration::DeviceConfiguration *result = 0 ;
  
  arg1 = (Efficio::Engine *)jarg1; 
  result = (Efficio::Configuration::DeviceConfiguration *)& ((arg1)->DeviceConfiguration);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_new_LeapConfiguration___() {
  void * jresult ;
  Efficio::Configuration::LeapConfiguration *result = 0 ;
  
  result = (Efficio::Configuration::LeapConfiguration *)new Efficio::Configuration::LeapConfiguration();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_delete_LeapConfiguration___(void * jarg1) {
  Efficio::Configuration::LeapConfiguration *arg1 = (Efficio::Configuration::LeapConfiguration *) 0 ;
  
  arg1 = (Efficio::Configuration::LeapConfiguration *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_LeapConfiguration_Enabled_set___(void * jarg1, unsigned int jarg2) {
  Efficio::Configuration::LeapConfiguration *arg1 = (Efficio::Configuration::LeapConfiguration *) 0 ;
  bool arg2 ;
  
  arg1 = (Efficio::Configuration::LeapConfiguration *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->Enabled = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_EfficiofRuntime_LeapConfiguration_Enabled_get___(void * jarg1) {
  unsigned int jresult ;
  Efficio::Configuration::LeapConfiguration *arg1 = (Efficio::Configuration::LeapConfiguration *) 0 ;
  bool result;
  
  arg1 = (Efficio::Configuration::LeapConfiguration *)jarg1; 
  result = (bool) ((arg1)->Enabled);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_new_DeviceConfiguration___() {
  void * jresult ;
  Efficio::Configuration::DeviceConfiguration *result = 0 ;
  
  result = (Efficio::Configuration::DeviceConfiguration *)new Efficio::Configuration::DeviceConfiguration();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_delete_DeviceConfiguration___(void * jarg1) {
  Efficio::Configuration::DeviceConfiguration *arg1 = (Efficio::Configuration::DeviceConfiguration *) 0 ;
  
  arg1 = (Efficio::Configuration::DeviceConfiguration *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_DeviceConfiguration_LeapConfiguration_set___(void * jarg1, void * jarg2) {
  Efficio::Configuration::DeviceConfiguration *arg1 = (Efficio::Configuration::DeviceConfiguration *) 0 ;
  Efficio::Configuration::LeapConfiguration *arg2 = (Efficio::Configuration::LeapConfiguration *) 0 ;
  
  arg1 = (Efficio::Configuration::DeviceConfiguration *)jarg1; 
  arg2 = (Efficio::Configuration::LeapConfiguration *)jarg2; 
  if (arg1) (arg1)->LeapConfiguration = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_DeviceConfiguration_LeapConfiguration_get___(void * jarg1) {
  void * jresult ;
  Efficio::Configuration::DeviceConfiguration *arg1 = (Efficio::Configuration::DeviceConfiguration *) 0 ;
  Efficio::Configuration::LeapConfiguration *result = 0 ;
  
  arg1 = (Efficio::Configuration::DeviceConfiguration *)jarg1; 
  result = (Efficio::Configuration::LeapConfiguration *)& ((arg1)->LeapConfiguration);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_Clear___(void * jarg1) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_Add___(void * jarg1, void * jarg2) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  std::shared_ptr< Efficio::Event > *arg2 = 0 ;
  std::shared_ptr< Efficio::Event > tempnull2 ;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  arg2 = jarg2 ? (std::shared_ptr< Efficio::Event > *)jarg2 : &tempnull2; 
  (arg1)->push_back((std::shared_ptr< Efficio::Event > const &)*arg2);
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_size___(void * jarg1) {
  unsigned long jresult ;
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  std::vector< std::shared_ptr< Efficio::Event > >::size_type result;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  result = ((std::vector< std::shared_ptr< Efficio::Event > > const *)arg1)->size();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_capacity___(void * jarg1) {
  unsigned long jresult ;
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  std::vector< std::shared_ptr< Efficio::Event > >::size_type result;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  result = ((std::vector< std::shared_ptr< Efficio::Event > > const *)arg1)->capacity();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_reserve___(void * jarg1, unsigned long jarg2) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  std::vector< std::shared_ptr< Efficio::Event > >::size_type arg2 ;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  arg2 = (std::vector< std::shared_ptr< Efficio::Event > >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_new_EventCollection__SWIG_0___() {
  void * jresult ;
  std::vector< std::shared_ptr< Efficio::Event > > *result = 0 ;
  
  result = (std::vector< std::shared_ptr< Efficio::Event > > *)new std::vector< std::shared_ptr< Efficio::Event > >();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_new_EventCollection__SWIG_1___(void * jarg1) {
  void * jresult ;
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = 0 ;
  std::vector< std::shared_ptr< Efficio::Event > > *result = 0 ;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< std::shared_ptr< Efficio::Event > > const & type is null", 0);
    return 0;
  } 
  result = (std::vector< std::shared_ptr< Efficio::Event > > *)new std::vector< std::shared_ptr< Efficio::Event > >((std::vector< std::shared_ptr< Efficio::Event > > const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_new_EventCollection__SWIG_2___(int jarg1) {
  void * jresult ;
  int arg1 ;
  std::vector< std::shared_ptr< Efficio::Event > > *result = 0 ;
  
  arg1 = (int)jarg1; 
  try {
    result = (std::vector< std::shared_ptr< Efficio::Event > > *)new_std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg___SWIG_2(arg1);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_getitemcopy___(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  int arg2 ;
  std::shared_ptr< Efficio::Event > result;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__getitemcopy(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = result ? new std::shared_ptr< Efficio::Event >(result) : 0; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_getitem___(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  int arg2 ;
  std::shared_ptr< Efficio::Event > *result = 0 ;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::shared_ptr< Efficio::Event > *) &std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__getitem(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = *result ? new std::shared_ptr< Efficio::Event >(*result) : 0; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_setitem___(void * jarg1, int jarg2, void * jarg3) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  int arg2 ;
  std::shared_ptr< Efficio::Event > *arg3 = 0 ;
  std::shared_ptr< Efficio::Event > tempnull3 ;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = jarg3 ? (std::shared_ptr< Efficio::Event > *)jarg3 : &tempnull3; 
  try {
    std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__setitem(arg1,arg2,(std::shared_ptr< Efficio::Event > const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_AddRange___(void * jarg1, void * jarg2) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  std::vector< std::shared_ptr< Efficio::Event > > *arg2 = 0 ;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  arg2 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< std::shared_ptr< Efficio::Event > > const & type is null", 0);
    return ;
  } 
  std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__AddRange(arg1,(std::vector< std::shared_ptr< Efficio::Event > > const &)*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_GetRange___(void * jarg1, int jarg2, int jarg3) {
  void * jresult ;
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  int arg2 ;
  int arg3 ;
  std::vector< std::shared_ptr< Efficio::Event > > *result = 0 ;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    result = (std::vector< std::shared_ptr< Efficio::Event > > *)std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__GetRange(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_Insert___(void * jarg1, int jarg2, void * jarg3) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  int arg2 ;
  std::shared_ptr< Efficio::Event > *arg3 = 0 ;
  std::shared_ptr< Efficio::Event > tempnull3 ;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = jarg3 ? (std::shared_ptr< Efficio::Event > *)jarg3 : &tempnull3; 
  try {
    std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__Insert(arg1,arg2,(std::shared_ptr< Efficio::Event > const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_InsertRange___(void * jarg1, int jarg2, void * jarg3) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  int arg2 ;
  std::vector< std::shared_ptr< Efficio::Event > > *arg3 = 0 ;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< std::shared_ptr< Efficio::Event > > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__InsertRange(arg1,arg2,(std::vector< std::shared_ptr< Efficio::Event > > const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_RemoveAt___(void * jarg1, int jarg2) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  int arg2 ;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__RemoveAt(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_RemoveRange___(void * jarg1, int jarg2, int jarg3) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__RemoveRange(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
  
}


SWIGEXPORT void * SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_Repeat___(void * jarg1, int jarg2) {
  void * jresult ;
  std::shared_ptr< Efficio::Event > *arg1 = 0 ;
  int arg2 ;
  std::shared_ptr< Efficio::Event > tempnull1 ;
  std::vector< std::shared_ptr< Efficio::Event > > *result = 0 ;
  
  arg1 = jarg1 ? (std::shared_ptr< Efficio::Event > *)jarg1 : &tempnull1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< std::shared_ptr< Efficio::Event > > *)std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__Repeat((std::shared_ptr< Efficio::Event > const &)*arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_Reverse__SWIG_0___(void * jarg1) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__Reverse__SWIG_0(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_Reverse__SWIG_1___(void * jarg1, int jarg2, int jarg3) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__Reverse__SWIG_1(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_EventCollection_SetRange___(void * jarg1, int jarg2, void * jarg3) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  int arg2 ;
  std::vector< std::shared_ptr< Efficio::Event > > *arg3 = 0 ;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< std::shared_ptr< Efficio::Event > > const & type is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_std_shared_ptr_Sl_Efficio_Event_Sg__Sg__SetRange(arg1,arg2,(std::vector< std::shared_ptr< Efficio::Event > > const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_EfficiofRuntime_delete_EventCollection___(void * jarg1) {
  std::vector< std::shared_ptr< Efficio::Event > > *arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *) 0 ;
  
  arg1 = (std::vector< std::shared_ptr< Efficio::Event > > *)jarg1; 
  delete arg1;
}


SWIGEXPORT std::shared_ptr< Efficio::Event > * SWIGSTDCALL CSharp_EfficiofRuntime_PinchEvent_SWIGSmartPtrUpcast___(std::shared_ptr< Efficio::Body::Hands::PinchEvent > *jarg1) {
    return jarg1 ? new std::shared_ptr< Efficio::Event >(*jarg1) : 0;
}

SWIGEXPORT Efficio::Frame * SWIGSTDCALL CSharp_EfficiofRuntime_EfficioFrame_SWIGUpcast___(Efficio::EfficioFrame *jarg1) {
    return (Efficio::Frame *)jarg1;
}

#ifdef __cplusplus
}
#endif

