//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Efficio.Net {

public class GestureCollection : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<Gesture>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GestureCollection(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GestureCollection obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GestureCollection() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EfficioPINVOKE.delete_GestureCollection(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public GestureCollection(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Gesture element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Gesture this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Gesture[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Gesture[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Gesture[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<Gesture> global::System.Collections.Generic.IEnumerable<Gesture>.GetEnumerator() {
    return new GestureCollectionEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new GestureCollectionEnumerator(this);
  }

  public GestureCollectionEnumerator GetEnumerator() {
    return new GestureCollectionEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class GestureCollectionEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Gesture>
  {
    private GestureCollection collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public GestureCollectionEnumerator(GestureCollection collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Gesture Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Gesture)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    EfficioPINVOKE.GestureCollection_Clear(swigCPtr);
  }

  public void Add(Gesture x) {
    EfficioPINVOKE.GestureCollection_Add(swigCPtr, Gesture.getCPtr(x));
    if (EfficioPINVOKE.SWIGPendingException.Pending) throw EfficioPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = EfficioPINVOKE.GestureCollection_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = EfficioPINVOKE.GestureCollection_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    EfficioPINVOKE.GestureCollection_reserve(swigCPtr, n);
  }

  public GestureCollection() : this(EfficioPINVOKE.new_GestureCollection__SWIG_0(), true) {
  }

  public GestureCollection(GestureCollection other) : this(EfficioPINVOKE.new_GestureCollection__SWIG_1(GestureCollection.getCPtr(other)), true) {
    if (EfficioPINVOKE.SWIGPendingException.Pending) throw EfficioPINVOKE.SWIGPendingException.Retrieve();
  }

  public GestureCollection(int capacity) : this(EfficioPINVOKE.new_GestureCollection__SWIG_2(capacity), true) {
    if (EfficioPINVOKE.SWIGPendingException.Pending) throw EfficioPINVOKE.SWIGPendingException.Retrieve();
  }

  private Gesture getitemcopy(int index) {
    global::System.IntPtr cPtr = EfficioPINVOKE.GestureCollection_getitemcopy(swigCPtr, index);
    Gesture ret = (cPtr == global::System.IntPtr.Zero) ? null : new Gesture(cPtr, true);
    if (EfficioPINVOKE.SWIGPendingException.Pending) throw EfficioPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Gesture getitem(int index) {
    global::System.IntPtr cPtr = EfficioPINVOKE.GestureCollection_getitem(swigCPtr, index);
    Gesture ret = (cPtr == global::System.IntPtr.Zero) ? null : new Gesture(cPtr, true);
    if (EfficioPINVOKE.SWIGPendingException.Pending) throw EfficioPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Gesture val) {
    EfficioPINVOKE.GestureCollection_setitem(swigCPtr, index, Gesture.getCPtr(val));
    if (EfficioPINVOKE.SWIGPendingException.Pending) throw EfficioPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(GestureCollection values) {
    EfficioPINVOKE.GestureCollection_AddRange(swigCPtr, GestureCollection.getCPtr(values));
    if (EfficioPINVOKE.SWIGPendingException.Pending) throw EfficioPINVOKE.SWIGPendingException.Retrieve();
  }

  public GestureCollection GetRange(int index, int count) {
    global::System.IntPtr cPtr = EfficioPINVOKE.GestureCollection_GetRange(swigCPtr, index, count);
    GestureCollection ret = (cPtr == global::System.IntPtr.Zero) ? null : new GestureCollection(cPtr, true);
    if (EfficioPINVOKE.SWIGPendingException.Pending) throw EfficioPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Gesture x) {
    EfficioPINVOKE.GestureCollection_Insert(swigCPtr, index, Gesture.getCPtr(x));
    if (EfficioPINVOKE.SWIGPendingException.Pending) throw EfficioPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, GestureCollection values) {
    EfficioPINVOKE.GestureCollection_InsertRange(swigCPtr, index, GestureCollection.getCPtr(values));
    if (EfficioPINVOKE.SWIGPendingException.Pending) throw EfficioPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    EfficioPINVOKE.GestureCollection_RemoveAt(swigCPtr, index);
    if (EfficioPINVOKE.SWIGPendingException.Pending) throw EfficioPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    EfficioPINVOKE.GestureCollection_RemoveRange(swigCPtr, index, count);
    if (EfficioPINVOKE.SWIGPendingException.Pending) throw EfficioPINVOKE.SWIGPendingException.Retrieve();
  }

  public static GestureCollection Repeat(Gesture value, int count) {
    global::System.IntPtr cPtr = EfficioPINVOKE.GestureCollection_Repeat(Gesture.getCPtr(value), count);
    GestureCollection ret = (cPtr == global::System.IntPtr.Zero) ? null : new GestureCollection(cPtr, true);
    if (EfficioPINVOKE.SWIGPendingException.Pending) throw EfficioPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    EfficioPINVOKE.GestureCollection_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    EfficioPINVOKE.GestureCollection_Reverse__SWIG_1(swigCPtr, index, count);
    if (EfficioPINVOKE.SWIGPendingException.Pending) throw EfficioPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, GestureCollection values) {
    EfficioPINVOKE.GestureCollection_SetRange(swigCPtr, index, GestureCollection.getCPtr(values));
    if (EfficioPINVOKE.SWIGPendingException.Pending) throw EfficioPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
