/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio;

public class AssetCollection {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AssetCollection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AssetCollection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EfficioRuntimeJNI.delete_AssetCollection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AssetCollection() {
    this(EfficioRuntimeJNI.new_AssetCollection__SWIG_0(), true);
  }

  public AssetCollection(long n) {
    this(EfficioRuntimeJNI.new_AssetCollection__SWIG_1(n), true);
  }

  public long size() {
    return EfficioRuntimeJNI.AssetCollection_size(swigCPtr, this);
  }

  public long capacity() {
    return EfficioRuntimeJNI.AssetCollection_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    EfficioRuntimeJNI.AssetCollection_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return EfficioRuntimeJNI.AssetCollection_isEmpty(swigCPtr, this);
  }

  public void clear() {
    EfficioRuntimeJNI.AssetCollection_clear(swigCPtr, this);
  }

  public void add(Asset x) {
    EfficioRuntimeJNI.AssetCollection_add(swigCPtr, this, Asset.getCPtr(x), x);
  }

  public Asset get(int i) {
    long cPtr = EfficioRuntimeJNI.AssetCollection_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Asset(cPtr, true);
  }

  public void set(int i, Asset val) {
    EfficioRuntimeJNI.AssetCollection_set(swigCPtr, this, i, Asset.getCPtr(val), val);
  }

}
