/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio;

public class Asset {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected Asset(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Asset obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EfficioRuntimeJNI.delete_Asset(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Asset(String name) {
    this(EfficioRuntimeJNI.new_Asset(name), true);
  }

  public void setSensors(SensorCollection value) {
    EfficioRuntimeJNI.Asset_Sensors_set(swigCPtr, this, SensorCollection.getCPtr(value), value);
  }

  public SensorCollection getSensors() {
    long cPtr = EfficioRuntimeJNI.Asset_Sensors_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SensorCollection(cPtr, false);
  }

  public String GetName() {
    return EfficioRuntimeJNI.Asset_GetName(swigCPtr, this);
  }

}
