/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio;

public final class GestureType {
  public final static GestureType Discrete = new GestureType("Discrete");
  public final static GestureType Continuous = new GestureType("Continuous");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GestureType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GestureType.class + " with value " + swigValue);
  }

  private GestureType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GestureType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GestureType(String swigName, GestureType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GestureType[] swigValues = { Discrete, Continuous };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

