/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio;

public class HandSupine extends DiscreteGesture {
  private transient long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected HandSupine(long cPtr, boolean cMemoryOwn) {
    super(EfficioRuntimeJNI.HandSupine_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HandSupine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        EfficioRuntimeJNI.delete_HandSupine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public HandSupine(String source, BodySide side, int handID) {
    this(EfficioRuntimeJNI.new_HandSupine(source, side.swigValue(), handID), true);
  }

  public EventType GetEventType() {
    return EventType.swigToEnum(EfficioRuntimeJNI.HandSupine_GetEventType(swigCPtr, this));
  }

  public void setSide(BodySide value) {
    EfficioRuntimeJNI.HandSupine_Side_set(swigCPtr, this, value.swigValue());
  }

  public BodySide getSide() {
    return BodySide.swigToEnum(EfficioRuntimeJNI.HandSupine_Side_get(swigCPtr, this));
  }

  public void setHandID(int value) {
    EfficioRuntimeJNI.HandSupine_HandID_set(swigCPtr, this, value);
  }

  public int getHandID() {
    return EfficioRuntimeJNI.HandSupine_HandID_get(swigCPtr, this);
  }

}
