/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio;

public class HandCollection {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HandCollection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HandCollection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EfficioRuntimeJNI.delete_HandCollection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public HandCollection() {
    this(EfficioRuntimeJNI.new_HandCollection__SWIG_0(), true);
  }

  public HandCollection(long n) {
    this(EfficioRuntimeJNI.new_HandCollection__SWIG_1(n), true);
  }

  public long size() {
    return EfficioRuntimeJNI.HandCollection_size(swigCPtr, this);
  }

  public long capacity() {
    return EfficioRuntimeJNI.HandCollection_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    EfficioRuntimeJNI.HandCollection_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return EfficioRuntimeJNI.HandCollection_isEmpty(swigCPtr, this);
  }

  public void clear() {
    EfficioRuntimeJNI.HandCollection_clear(swigCPtr, this);
  }

  public void add(Hand x) {
    EfficioRuntimeJNI.HandCollection_add(swigCPtr, this, Hand.getCPtr(x), x);
  }

  public Hand get(int i) {
    return new Hand(EfficioRuntimeJNI.HandCollection_get(swigCPtr, this, i), false);
  }

  public void set(int i, Hand val) {
    EfficioRuntimeJNI.HandCollection_set(swigCPtr, this, i, Hand.getCPtr(val), val);
  }

}
