/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio;

public class JointCollection {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected JointCollection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JointCollection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EfficioRuntimeJNI.delete_JointCollection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public JointCollection() {
    this(EfficioRuntimeJNI.new_JointCollection__SWIG_0(), true);
  }

  public JointCollection(long n) {
    this(EfficioRuntimeJNI.new_JointCollection__SWIG_1(n), true);
  }

  public long size() {
    return EfficioRuntimeJNI.JointCollection_size(swigCPtr, this);
  }

  public long capacity() {
    return EfficioRuntimeJNI.JointCollection_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    EfficioRuntimeJNI.JointCollection_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return EfficioRuntimeJNI.JointCollection_isEmpty(swigCPtr, this);
  }

  public void clear() {
    EfficioRuntimeJNI.JointCollection_clear(swigCPtr, this);
  }

  public void add(Joint x) {
    EfficioRuntimeJNI.JointCollection_add(swigCPtr, this, Joint.getCPtr(x), x);
  }

  public Joint get(int i) {
    return new Joint(EfficioRuntimeJNI.JointCollection_get(swigCPtr, this, i), false);
  }

  public void set(int i, Joint val) {
    EfficioRuntimeJNI.JointCollection_set(swigCPtr, this, i, Joint.getCPtr(val), val);
  }

}
