/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Runtime;

public final class BodyTrackingType {
  public final static BodyTrackingType Eye = new BodyTrackingType("Eye");
  public final static BodyTrackingType Face = new BodyTrackingType("Face");
  public final static BodyTrackingType Hand = new BodyTrackingType("Hand");
  public final static BodyTrackingType Arm = new BodyTrackingType("Arm");
  public final static BodyTrackingType Body = new BodyTrackingType("Body");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BodyTrackingType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BodyTrackingType.class + " with value " + swigValue);
  }

  private BodyTrackingType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BodyTrackingType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BodyTrackingType(String swigName, BodyTrackingType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BodyTrackingType[] swigValues = { Eye, Face, Hand, Arm, Body };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

