/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public class DataDictionary {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DataDictionary(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataDictionary obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EfficioJNI.delete_DataDictionary(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DataDictionary() {
    this(EfficioJNI.new_DataDictionary__SWIG_0(), true);
  }

  public DataDictionary(DataDictionary arg0) {
    this(EfficioJNI.new_DataDictionary__SWIG_1(DataDictionary.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return EfficioJNI.DataDictionary_size(swigCPtr, this);
  }

  public boolean empty() {
    return EfficioJNI.DataDictionary_empty(swigCPtr, this);
  }

  public void clear() {
    EfficioJNI.DataDictionary_clear(swigCPtr, this);
  }

  public DataCollection get(DataType key) {
    return new DataCollection(EfficioJNI.DataDictionary_get(swigCPtr, this, key.swigValue()), false);
  }

  public void set(DataType key, DataCollection x) {
    EfficioJNI.DataDictionary_set(swigCPtr, this, key.swigValue(), DataCollection.getCPtr(x), x);
  }

  public void del(DataType key) {
    EfficioJNI.DataDictionary_del(swigCPtr, this, key.swigValue());
  }

  public boolean has_key(DataType key) {
    return EfficioJNI.DataDictionary_has_key(swigCPtr, this, key.swigValue());
  }

}
