/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public final class DeviceStatus {
  public final static DeviceStatus Unknown = new DeviceStatus("Unknown");
  public final static DeviceStatus Disabled = new DeviceStatus("Disabled");
  public final static DeviceStatus Faulted = new DeviceStatus("Faulted");
  public final static DeviceStatus Disconnected = new DeviceStatus("Disconnected");
  public final static DeviceStatus Connecting = new DeviceStatus("Connecting");
  public final static DeviceStatus Connected = new DeviceStatus("Connected");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DeviceStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DeviceStatus.class + " with value " + swigValue);
  }

  private DeviceStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DeviceStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DeviceStatus(String swigName, DeviceStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DeviceStatus[] swigValues = { Unknown, Disabled, Faulted, Disconnected, Connecting, Connected };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

