/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public class EfficioFrame extends Frame {
  private transient long swigCPtr;

  protected EfficioFrame(long cPtr, boolean cMemoryOwn) {
    super(EfficioJNI.EfficioFrame_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EfficioFrame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EfficioJNI.delete_EfficioFrame(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public EfficioFrame(int ID) {
    this(EfficioJNI.new_EfficioFrame(ID), true);
  }

  public EventCollection GetEvents() {
    return new EventCollection(EfficioJNI.EfficioFrame_GetEvents(swigCPtr, this), true);
  }

  public void AddEvent(SWIGTYPE_p_std__shared_ptrT_Efficio__Events__Event_t eventPtr) {
    EfficioJNI.EfficioFrame_AddEvent(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_Efficio__Events__Event_t.getCPtr(eventPtr));
  }

  public void setID(int value) {
    EfficioJNI.EfficioFrame_ID_set(swigCPtr, this, value);
  }

  public int getID() {
    return EfficioJNI.EfficioFrame_ID_get(swigCPtr, this);
  }

}
