/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Runtime;

public class EfficioFrame extends Frame {
  private transient long swigCPtr;

  protected EfficioFrame(long cPtr, boolean cMemoryOwn) {
    super(EfficioRuntimeJNI.EfficioFrame_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EfficioFrame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EfficioRuntimeJNI.delete_EfficioFrame(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public EfficioFrame() {
    this(EfficioRuntimeJNI.new_EfficioFrame(), true);
  }

  public EventCollection GetEvents() {
    return new EventCollection(EfficioRuntimeJNI.EfficioFrame_GetEvents(swigCPtr, this), true);
  }

  public void AddEvent(Event eventPtr) {
    EfficioRuntimeJNI.EfficioFrame_AddEvent(swigCPtr, this, Event.getCPtr(eventPtr), eventPtr);
  }

}
