/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public class Finger {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Finger(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Finger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EfficioJNI.delete_Finger(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Finger(SWIGTYPE_p_Efficio__Models__Body__FingerType fingerType, SWIGTYPE_p_arrayT_std__shared_ptrT_Efficio__Models__Body__Joint_t_4_t joints) {
    this(EfficioJNI.new_Finger(SWIGTYPE_p_Efficio__Models__Body__FingerType.getCPtr(fingerType), SWIGTYPE_p_arrayT_std__shared_ptrT_Efficio__Models__Body__Joint_t_4_t.getCPtr(joints)), true);
  }

  public SWIGTYPE_p_arrayT_std__shared_ptrT_Efficio__Models__Body__Joint_t_4_t getJoints() {
    return new SWIGTYPE_p_arrayT_std__shared_ptrT_Efficio__Models__Body__Joint_t_4_t(EfficioJNI.Finger_Joints_get(swigCPtr, this), true);
  }

  public SWIGTYPE_p_FingerType getFingerType() {
    return new SWIGTYPE_p_FingerType(EfficioJNI.Finger_FingerType_get(swigCPtr, this), true);
  }

}
