/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public class FingerCollection {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FingerCollection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FingerCollection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EfficioJNI.delete_FingerCollection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FingerCollection() {
    this(EfficioJNI.new_FingerCollection__SWIG_0(), true);
  }

  public FingerCollection(long n) {
    this(EfficioJNI.new_FingerCollection__SWIG_1(n), true);
  }

  public long size() {
    return EfficioJNI.FingerCollection_size(swigCPtr, this);
  }

  public long capacity() {
    return EfficioJNI.FingerCollection_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    EfficioJNI.FingerCollection_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return EfficioJNI.FingerCollection_isEmpty(swigCPtr, this);
  }

  public void clear() {
    EfficioJNI.FingerCollection_clear(swigCPtr, this);
  }

  public void add(SWIGTYPE_p_std__shared_ptrT_Efficio__Models__Human__Finger_t x) {
    EfficioJNI.FingerCollection_add(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_Efficio__Models__Human__Finger_t.getCPtr(x));
  }

  public SWIGTYPE_p_std__shared_ptrT_Efficio__Models__Human__Finger_t get(int i) {
    return new SWIGTYPE_p_std__shared_ptrT_Efficio__Models__Human__Finger_t(EfficioJNI.FingerCollection_get(swigCPtr, this, i), false);
  }

  public void set(int i, SWIGTYPE_p_std__shared_ptrT_Efficio__Models__Human__Finger_t val) {
    EfficioJNI.FingerCollection_set(swigCPtr, this, i, SWIGTYPE_p_std__shared_ptrT_Efficio__Models__Human__Finger_t.getCPtr(val));
  }

}
