/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public final class Finger {
  public final static Finger Thumb = new Finger("Thumb");
  public final static Finger Index = new Finger("Index");
  public final static Finger Middle = new Finger("Middle");
  public final static Finger Ring = new Finger("Ring");
  public final static Finger Pinky = new Finger("Pinky");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Finger swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Finger.class + " with value " + swigValue);
  }

  private Finger(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Finger(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Finger(String swigName, Finger swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Finger[] swigValues = { Thumb, Index, Middle, Ring, Pinky };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

