/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public class Finger {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Finger(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Finger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EfficioJNI.delete_Finger(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Finger(SWIGTYPE_p_Efficio__Models__Body__FingerType fingerType, Joint tip, Joint dip, Joint mcp, Joint pip) {
    this(EfficioJNI.new_Finger(SWIGTYPE_p_Efficio__Models__Body__FingerType.getCPtr(fingerType), Joint.getCPtr(tip), tip, Joint.getCPtr(dip), dip, Joint.getCPtr(mcp), mcp, Joint.getCPtr(pip), pip), true);
  }

  public Joint getTip() {
    long cPtr = EfficioJNI.Finger_Tip_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Joint(cPtr, false);
  }

  public Joint getDIP() {
    long cPtr = EfficioJNI.Finger_DIP_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Joint(cPtr, false);
  }

  public Joint getMCP() {
    long cPtr = EfficioJNI.Finger_MCP_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Joint(cPtr, false);
  }

  public Joint getPIP() {
    long cPtr = EfficioJNI.Finger_PIP_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Joint(cPtr, false);
  }

  public SWIGTYPE_p_FingerType getFingerType() {
    return new SWIGTYPE_p_FingerType(EfficioJNI.Finger_FingerType_get(swigCPtr, this), true);
  }

}
