/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public class Frame {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected Frame(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Frame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EfficioJNI.delete_Frame(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Frame() {
    this(EfficioJNI.new_Frame(), true);
  }

  public SWIGTYPE_p_std__mapT_Efficio__Data__DataType_std__vectorT_std__shared_ptrT_Efficio__Data__Data_t_t_t GetData() {
    return new SWIGTYPE_p_std__mapT_Efficio__Data__DataType_std__vectorT_std__shared_ptrT_Efficio__Data__Data_t_t_t(EfficioJNI.Frame_GetData(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_std__shared_ptrT_Efficio__Data__Data_t_t GetDataOfType(SWIGTYPE_p_Efficio__Data__DataType dataType) {
    return new SWIGTYPE_p_std__vectorT_std__shared_ptrT_Efficio__Data__Data_t_t(EfficioJNI.Frame_GetDataOfType(swigCPtr, this, SWIGTYPE_p_Efficio__Data__DataType.getCPtr(dataType)), true);
  }

  public void AddData(SWIGTYPE_p_std__vectorT_std__shared_ptrT_Efficio__Data__Data_t_t data) {
    EfficioJNI.Frame_AddData(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__shared_ptrT_Efficio__Data__Data_t_t.getCPtr(data));
  }

  public void AddFrame(Frame frame) {
    EfficioJNI.Frame_AddFrame(swigCPtr, this, Frame.getCPtr(frame), frame);
  }

}
