/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public class Frame {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected Frame(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Frame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EfficioJNI.delete_Frame(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Frame() {
    this(EfficioJNI.new_Frame(), true);
  }

  public void setHandData(HandData value) {
    EfficioJNI.Frame_HandData_set(swigCPtr, this, HandData.getCPtr(value), value);
  }

  public HandData getHandData() {
    long cPtr = EfficioJNI.Frame_HandData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new HandData(cPtr, false);
  }

}
