/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public class HandData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HandData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HandData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EfficioJNI.delete_HandData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public HandData() {
    this(EfficioJNI.new_HandData(), true);
  }

  public void setHands(SWIGTYPE_p_std__vectorT_Efficio__Models__Human__Hand_t value) {
    EfficioJNI.HandData_Hands_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_Efficio__Models__Human__Hand_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_Efficio__Models__Human__Hand_t getHands() {
    long cPtr = EfficioJNI.HandData_Hands_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_Efficio__Models__Human__Hand_t(cPtr, false);
  }

}
