/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public class Hand {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Hand(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Hand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EfficioJNI.delete_Hand(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Hand() {
    this(EfficioJNI.new_Hand__SWIG_0(), true);
  }

  public Hand(SWIGTYPE_p_std__arrayT_Efficio__Models__Human__Finger_5_t fingers, BodySide side) {
    this(EfficioJNI.new_Hand__SWIG_1(SWIGTYPE_p_std__arrayT_Efficio__Models__Human__Finger_5_t.getCPtr(fingers), side.swigValue()), true);
  }

  public void setFingers(SWIGTYPE_p_std__arrayT_Efficio__Models__Human__Finger_5_t value) {
    EfficioJNI.Hand_Fingers_set(swigCPtr, this, SWIGTYPE_p_std__arrayT_Efficio__Models__Human__Finger_5_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__arrayT_Efficio__Models__Human__Finger_5_t getFingers() {
    return new SWIGTYPE_p_std__arrayT_Efficio__Models__Human__Finger_5_t(EfficioJNI.Hand_Fingers_get(swigCPtr, this), true);
  }

  public void setSide(BodySide value) {
    EfficioJNI.Hand_Side_set(swigCPtr, this, value.swigValue());
  }

  public BodySide getSide() {
    return BodySide.swigToEnum(EfficioJNI.Hand_Side_get(swigCPtr, this));
  }

  public SWIGTYPE_p_std__vectorT_Efficio__Models__Human__Finger_t GetFingers() {
    return new SWIGTYPE_p_std__vectorT_Efficio__Models__Human__Finger_t(EfficioJNI.Hand_GetFingers(swigCPtr, this), true);
  }

}
