/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Runtime;

public class PinchEvent extends Event {
  private transient long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected PinchEvent(long cPtr, boolean cMemoryOwn) {
    super(EfficioRuntimeJNI.PinchEvent_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PinchEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        EfficioRuntimeJNI.delete_PinchEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PinchEvent(BodySide side, Vector3 position) {
    this(EfficioRuntimeJNI.new_PinchEvent(side.swigValue(), Vector3.getCPtr(position), position), true);
  }

  public BodySide Side() {
    return BodySide.swigToEnum(EfficioRuntimeJNI.PinchEvent_Side(swigCPtr, this));
  }

  public String Finger1() {
    return EfficioRuntimeJNI.PinchEvent_Finger1(swigCPtr, this);
  }

  public String Finger2() {
    return EfficioRuntimeJNI.PinchEvent_Finger2(swigCPtr, this);
  }

  public Vector3 Position() {
    return new Vector3(EfficioRuntimeJNI.PinchEvent_Position(swigCPtr, this), true);
  }

}
