/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public class RightHandThumbAndIndexPinch extends Pinch {
  private transient long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected RightHandThumbAndIndexPinch(long cPtr, boolean cMemoryOwn) {
    super(EfficioJNI.RightHandThumbAndIndexPinch_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RightHandThumbAndIndexPinch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        EfficioJNI.delete_RightHandThumbAndIndexPinch(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RightHandThumbAndIndexPinch(Vector3 position) {
    this(EfficioJNI.new_RightHandThumbAndIndexPinch(Vector3.getCPtr(position), position), true);
  }

  public void Eh() {
    EfficioJNI.RightHandThumbAndIndexPinch_Eh(swigCPtr, this);
  }

}
