/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public class SingleHandGestureDetector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SingleHandGestureDetector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SingleHandGestureDetector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EfficioJNI.delete_SingleHandGestureDetector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GestureCollection Detect(SWIGTYPE_p_Leap__Hand hand) {
    return new GestureCollection(EfficioJNI.SingleHandGestureDetector_Detect(swigCPtr, this, SWIGTYPE_p_Leap__Hand.getCPtr(hand)), true);
  }

}
