/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public final class TrackingType {
  public final static TrackingType Unknown = new TrackingType("Unknown");
  public final static TrackingType Hand = new TrackingType("Hand");
  public final static TrackingType Eye = new TrackingType("Eye");
  public final static TrackingType Face = new TrackingType("Face");
  public final static TrackingType Body = new TrackingType("Body");
  public final static TrackingType Mind = new TrackingType("Mind");
  public final static TrackingType Image = new TrackingType("Image");
  public final static TrackingType Audio = new TrackingType("Audio");
  public final static TrackingType Speech = new TrackingType("Speech");
  public final static TrackingType Location = new TrackingType("Location");
  public final static TrackingType Orientation = new TrackingType("Orientation");
  public final static TrackingType Analogue = new TrackingType("Analogue");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TrackingType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TrackingType.class + " with value " + swigValue);
  }

  private TrackingType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TrackingType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TrackingType(String swigName, TrackingType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TrackingType[] swigValues = { Unknown, Hand, Eye, Face, Body, Mind, Image, Audio, Speech, Location, Orientation, Analogue };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

