/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public class Connected extends Event {
  private transient long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected Connected(long cPtr, boolean cMemoryOwn) {
    super(EfficioRuntimeJNI.Connected_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Connected obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        EfficioRuntimeJNI.delete_Connected(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Connected(SensorInformation details) {
    this(EfficioRuntimeJNI.new_Connected(SensorInformation.getCPtr(details), details), true);
  }

  public void setSensorInformation(SensorInformation value) {
    EfficioRuntimeJNI.Connected_SensorInformation_set(swigCPtr, this, SensorInformation.getCPtr(value), value);
  }

  public SensorInformation getSensorInformation() {
    long cPtr = EfficioRuntimeJNI.Connected_SensorInformation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SensorInformation(cPtr, false);
  }

  public EventType GetEventType() {
    return EventType.swigToEnum(EfficioRuntimeJNI.Connected_GetEventType(swigCPtr, this));
  }

}
