/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public class GearVRButtonPressed extends Event {
  private transient long swigCPtr;

  protected GearVRButtonPressed(long cPtr, boolean cMemoryOwn) {
    super(EfficioRuntimeJNI.GearVRButtonPressed_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GearVRButtonPressed obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EfficioRuntimeJNI.delete_GearVRButtonPressed(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GearVRButtonPressed() {
    this(EfficioRuntimeJNI.new_GearVRButtonPressed(), true);
  }

  public EventType GetEventType() {
    return EventType.swigToEnum(EfficioRuntimeJNI.GearVRButtonPressed_GetEventType(swigCPtr, this));
  }

}
