/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public class GearVRAction extends Event {
  private transient long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected GearVRAction(long cPtr, boolean cMemoryOwn) {
    super(EfficioRuntimeJNI.GearVRAction_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GearVRAction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        EfficioRuntimeJNI.delete_GearVRAction(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GearVRAction(ButtonType buttonType) {
    this(EfficioRuntimeJNI.new_GearVRAction(buttonType.swigValue()), true);
  }

  public void setButtonType(ButtonType value) {
    EfficioRuntimeJNI.GearVRAction_ButtonType_set(swigCPtr, this, value.swigValue());
  }

  public ButtonType getButtonType() {
    return ButtonType.swigToEnum(EfficioRuntimeJNI.GearVRAction_ButtonType_get(swigCPtr, this));
  }

  public EventType GetEventType() {
    return EventType.swigToEnum(EfficioRuntimeJNI.GearVRAction_GetEventType(swigCPtr, this));
  }

}
