/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public class Finger {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Finger(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Finger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EfficioJNI.delete_Finger(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Finger() {
    this(EfficioJNI.new_Finger__SWIG_0(), true);
  }

  public Finger(FingerType fingerType, boolean isExtended, float length, Joint tip, Joint dip, Joint mcp, Joint pip) {
    this(EfficioJNI.new_Finger__SWIG_1(fingerType.swigValue(), isExtended, length, Joint.getCPtr(tip), tip, Joint.getCPtr(dip), dip, Joint.getCPtr(mcp), mcp, Joint.getCPtr(pip), pip), true);
  }

  public void setTip(Joint value) {
    EfficioJNI.Finger_Tip_set(swigCPtr, this, Joint.getCPtr(value), value);
  }

  public Joint getTip() {
    long cPtr = EfficioJNI.Finger_Tip_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Joint(cPtr, false);
  }

  public void setDIP(Joint value) {
    EfficioJNI.Finger_DIP_set(swigCPtr, this, Joint.getCPtr(value), value);
  }

  public Joint getDIP() {
    long cPtr = EfficioJNI.Finger_DIP_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Joint(cPtr, false);
  }

  public void setMCP(Joint value) {
    EfficioJNI.Finger_MCP_set(swigCPtr, this, Joint.getCPtr(value), value);
  }

  public Joint getMCP() {
    long cPtr = EfficioJNI.Finger_MCP_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Joint(cPtr, false);
  }

  public void setPIP(Joint value) {
    EfficioJNI.Finger_PIP_set(swigCPtr, this, Joint.getCPtr(value), value);
  }

  public Joint getPIP() {
    long cPtr = EfficioJNI.Finger_PIP_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Joint(cPtr, false);
  }

  public void setValid(boolean value) {
    EfficioJNI.Finger_Valid_set(swigCPtr, this, value);
  }

  public boolean getValid() {
    return EfficioJNI.Finger_Valid_get(swigCPtr, this);
  }

  public void setFingerType(FingerType value) {
    EfficioJNI.Finger_FingerType_set(swigCPtr, this, value.swigValue());
  }

  public FingerType getFingerType() {
    return FingerType.swigToEnum(EfficioJNI.Finger_FingerType_get(swigCPtr, this));
  }

  public void setIsExtended(boolean value) {
    EfficioJNI.Finger_IsExtended_set(swigCPtr, this, value);
  }

  public boolean getIsExtended() {
    return EfficioJNI.Finger_IsExtended_get(swigCPtr, this);
  }

  public void setLength(float value) {
    EfficioJNI.Finger_Length_set(swigCPtr, this, value);
  }

  public float getLength() {
    return EfficioJNI.Finger_Length_get(swigCPtr, this);
  }

}
