/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Efficio.Java;

public final class Status {
  public final static Status Unknown = new Status("Unknown");
  public final static Status Uninitialized = new Status("Uninitialized");
  public final static Status Disabled = new Status("Disabled");
  public final static Status Faulted = new Status("Faulted");
  public final static Status Disconnected = new Status("Disconnected");
  public final static Status Connecting = new Status("Connecting");
  public final static Status Connected = new Status("Connected");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Status swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Status.class + " with value " + swigValue);
  }

  private Status(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Status(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Status(String swigName, Status swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Status[] swigValues = { Unknown, Uninitialized, Disabled, Faulted, Disconnected, Connecting, Connected };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

